apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-iam-deployment
spec:
  selector:
    matchLabels:
      app: ms-iam
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-iam
    spec:
      containers:
      - name: ms-iam
        image: pouch/ms-iam:dev
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "java -jar -Dspring.profiles.active=dev /app.jar; while true; do sleep 30; done;" ]
        ports:
        - containerPort: 8080
        volumeMounts:
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred